services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DB: mysqlDB
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
